# Generated by Django 5.0.3 on 2024-05-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gn_01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='player_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
