# Generated by Django 5.0.3 on 2024-05-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gn_01', '0002_movie_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='gn_01/videos/movies/movie_files/'),
        ),
    ]
